services:
  communication_module:
    image: communication_module
    build: 
      context: ./communication_module
      dockerfile: Dockerfile
    container_name: communication_module
    networks:
      - uav_net

  external_comms:
    image: external_comms
    build: 
      context: ./auxiliaries/external_comms
      dockerfile: Dockerfile
    container_name: external_comms
    depends_on:
      - communication_module
    volumes:
      - ./resources/external_comms_config.json:/app/config.json
    networks:
      - uav_net

  application:
    image: application
    build: 
      context: ./application
      dockerfile: Dockerfile
    container_name: application
    depends_on:
      - communication_module
      - uav_controller
    volumes:
      - ./resources/application_config.json:/app/config.json
    networks:
      - uav_net

  uav_controller:
    image: copter453
    build: 
      context: ./uav_controller/ardupilot4_5_3
      dockerfile: SITL
    container_name: uav_controller
    ports:
      - "9876:9876/udp"
      - "3400:3400/udp"
    depends_on:
      - communication_module
    volumes: 
      - ./resources/uav_controller_config.json:/app/config.json
    networks:
      - uav_net

networks:
  uav_net:
    driver: bridge