services:
  gateway:
    build: ./netsim_gateway
    ports:
      - "3000:3000/udp"
      - "3001:3001/udp"
    networks:
      - sim_net

  netsim_1:
    build: ./netsim
    networks:
      - sim_net

  netsim_2:
    build: ./netsim
    networks:
      - sim_net

  netsim_3:
    build: ./netsim
    networks:
      - sim_net

networks:
  sim_net:
    driver: bridge
