// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildImages'](arg1, arg2, arg3);
}

export function DiscardCurrentRun(arg1) {
  return window['go']['main']['App']['DiscardCurrentRun'](arg1);
}

export function DownloadLogs() {
  return window['go']['main']['App']['DownloadLogs']();
}

export function ExportSimulation(arg1, arg2) {
  return window['go']['main']['App']['ExportSimulation'](arg1, arg2);
}

export function GetAvailableControllers() {
  return window['go']['main']['App']['GetAvailableControllers']();
}

export function GetAvailableMixers() {
  return window['go']['main']['App']['GetAvailableMixers']();
}

export function GetAvailableServices() {
  return window['go']['main']['App']['GetAvailableServices']();
}

export function GetKmlFirstCoordinate(arg1) {
  return window['go']['main']['App']['GetKmlFirstCoordinate'](arg1);
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function LoadLogEntries() {
  return window['go']['main']['App']['LoadLogEntries']();
}

export function LoadSimulationConfig() {
  return window['go']['main']['App']['LoadSimulationConfig']();
}

export function SaveSimulationConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSimulationConfig'](arg1, arg2, arg3);
}

export function SearchLogs(arg1, arg2) {
  return window['go']['main']['App']['SearchLogs'](arg1, arg2);
}

export function SelectArduPilotInstance() {
  return window['go']['main']['App']['SelectArduPilotInstance']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectKubeConfig() {
  return window['go']['main']['App']['SelectKubeConfig']();
}

export function SendAlgorithmCommand(arg1, arg2) {
  return window['go']['main']['App']['SendAlgorithmCommand'](arg1, arg2);
}

export function StartSimulation(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSimulation'](arg1, arg2, arg3);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}
