// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function BuildImages(arg1:Array<domain.UAV>,arg2:domain.GeneralConfig,arg3:boolean):Promise<void>;

export function DiscardCurrentRun(arg1:domain.GeneralConfig):Promise<void>;

export function DownloadLogs():Promise<void>;

export function GetAvailableControllers():Promise<Array<domain.ServiceType>>;

export function GetAvailableMixers():Promise<Array<domain.ServiceType>>;

export function GetAvailableServices():Promise<Array<domain.ServiceType>>;

export function GetKmlFirstCoordinate(arg1:string):Promise<domain.Coordinate>;

export function LoadFile(arg1:string):Promise<string>;

export function LoadLogEntries():Promise<Array<string>>;

export function LoadSimulationConfig():Promise<domain.SimulationState>;

export function SaveSimulationConfig(arg1:Array<domain.UAV>,arg2:domain.GeneralConfig,arg3:string):Promise<void>;

export function SearchLogs(arg1:string,arg2:domain.LogFilter):Promise<Array<domain.LogMessage>>;

export function SelectArduPilotInstance():Promise<string>;

export function SelectFile():Promise<string>;

export function SendAlgorithmCommand(arg1:string,arg2:string):Promise<void>;

export function StartSimulation(arg1:Array<domain.UAV>,arg2:domain.GeneralConfig,arg3:boolean):Promise<void>;

export function StopSimulation():Promise<void>;
