// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableServices() {
  return window['go']['main']['App']['GetAvailableServices']();
}

export function GetKmlFirstCoordinate(arg1) {
  return window['go']['main']['App']['GetKmlFirstCoordinate'](arg1);
}

export function LoadSimulationConfig() {
  return window['go']['main']['App']['LoadSimulationConfig']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendAlgorithmCommand(arg1, arg2) {
  return window['go']['main']['App']['SendAlgorithmCommand'](arg1, arg2);
}

export function StartSimulation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSimulation'](arg1, arg2, arg3, arg4);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}
