// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulation} from '../models';

export function GetAvailableServices():Promise<Array<simulation.ServiceType>>;

export function LoadSimulationConfig():Promise<simulation.SimulationState>;

export function SelectFile():Promise<string>;

export function SendAlgorithmCommand(arg1:string,arg2:string):Promise<void>;

export function StartSimulation(arg1:Array<simulation.UAV>,arg2:simulation.GeneralConfig,arg3:string,arg4:boolean):Promise<void>;

export function StopSimulation():Promise<void>;
