// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableServices() {
  return window['go']['main']['App']['GetAvailableServices']();
}

export function StartSimulation(arg1, arg2) {
  return window['go']['main']['App']['StartSimulation'](arg1, arg2);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}
