// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulation} from '../models';

export function GetAvailableServices():Promise<Array<simulation.ServiceType>>;

export function StartSimulation(arg1:Array<simulation.UAV>,arg2:boolean):Promise<void>;

export function StopSimulation():Promise<void>;
