// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DiscardCurrentRun(arg1:domain.GeneralConfig):Promise<void>;

export function GetAvailableServices():Promise<Array<domain.ServiceType>>;

export function GetKmlFirstCoordinate(arg1:string):Promise<domain.Coordinate>;

export function LoadFile(arg1:string):Promise<string>;

export function LoadLogEntries():Promise<Array<string>>;

export function LoadLogEntry(arg1:string):Promise<Record<string, any>>;

export function LoadSimulationConfig():Promise<domain.SimulationState>;

export function SaveSimulationConfig(arg1:Array<domain.UAV>,arg2:domain.GeneralConfig,arg3:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SendAlgorithmCommand(arg1:string,arg2:string):Promise<void>;

export function StartSimulation(arg1:Array<domain.UAV>,arg2:domain.GeneralConfig,arg3:boolean):Promise<void>;

export function StopSimulation():Promise<void>;
